-- MySQL Script generated by MySQL Workbench
-- 04/18/21 10:25:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Database db_bukuhutang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Database db_bukuhutang
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `db_bukuhutang` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_bukuhutang` ;

-- -----------------------------------------------------
-- Table `db_bukuhutang`.`penghutang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bukuhutang`.`penghutang` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nama` VARCHAR(100) NOT NULL COMMENT '',
  `jk` ENUM('l', 'p') NOT NULL COMMENT '',
  `pekerjaan` VARCHAR(100) NULL COMMENT '',
  `no_hp` VARCHAR(13) NULL COMMENT '',
  `alamat` VARCHAR(225) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bukuhutang`.`hutang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bukuhutang`.`hutang` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nominal` INT NOT NULL COMMENT '',
  `tanggal` DATE NOT NULL COMMENT '',
  `ket` VARCHAR(225) NULL COMMENT '',
  `id_penghutang` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `id_penghutang`)  COMMENT '',
  INDEX `fk_hutang_id_penghutangx` (`id_penghutang` ASC)  COMMENT '',
  CONSTRAINT `fk_hutang_penghutang`
    FOREIGN KEY (`id_penghutang`)
    REFERENCES `db_bukuhutang`.`penghutang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bukuhutang`.`bayar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bukuhutang`.`bayar` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nominal` INT NOT NULL COMMENT '',
  `tanggal` DATE NOT NULL COMMENT '',
  `ket` VARCHAR(225) NULL COMMENT '',
  `id_penghutang` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `id_penghutang`)  COMMENT '',
  INDEX `fk_bayar_penghutang1_idx` (`id_penghutang` ASC)  COMMENT '',
  CONSTRAINT `fk_bayar_penghutang1`
    FOREIGN KEY (`id_penghutang`)
    REFERENCES `db_bukuhutang`.`penghutang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_bukuhutang`.`penghutang`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_bukuhutang`;
INSERT INTO `db_bukuhutang`.`penghutang` (`id`, `nama`, `jk`, `pekerjaan`, `no_hp`, `alamat`) VALUES (1, 'Arianrhod Comey', 'l', 'pedagang', '781-286-3454', '83753 Black-Throated Cardinal St');
INSERT INTO `db_bukuhutang`.`penghutang` (`id`, `nama`, `jk`, `pekerjaan`, `no_hp`, `alamat`) VALUES (2, 'Morgan Conway', 'l', 'petani', '874-562-8494', '30181 Grey Phalarope St');
INSERT INTO `db_bukuhutang`.`penghutang` (`id`, `nama`, `jk`, `pekerjaan`, `no_hp`, `alamat`) VALUES (3, 'Myf Cornog', 'p', 'dosen', '391-878-0982', '5 Arctic Hare St');
INSERT INTO `db_bukuhutang`.`penghutang` (`id`, `nama`, `jk`, `pekerjaan`, `no_hp`, `alamat`) VALUES (4, 'Lyn Jones', 'p', 'dokter', '743-378-5127', '765 Nyala St');
INSERT INTO `db_bukuhutang`.`penghutang` (`id`, `nama`, `jk`, `pekerjaan`, `no_hp`, `alamat`) VALUES (5, 'Betrys Evanson', 'p', 'sastrawan', '545-941-6549', '314 Neotropic Cormorant St');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_bukuhutang`.`hutang`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_bukuhutang`;
INSERT INTO `db_bukuhutang`.`hutang` (`id`, `nominal`, `tanggal`, `ket`, `id_penghutang`) VALUES (1, 20000, '2021-04-19', 'Tuku es jus ning Bi karti', 1);
INSERT INTO `db_bukuhutang`.`hutang` (`id`, `nominal`, `tanggal`, `ket`, `id_penghutang`) VALUES (2, 30000, '2021-04-19', 'Nyelang kanggo tuku bata', 3);
INSERT INTO `db_bukuhutang`.`hutang` (`id`, `nominal`, `tanggal`, `ket`, `id_penghutang`) VALUES (3, 25000, '2021-04-19', 'Gorengan gedang', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_bukuhutang`.`bayar`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_bukuhutang`;
INSERT INTO `db_bukuhutang`.`bayar` (`id`, `nominal`, `tanggal`, `ket`, `id_penghutang`) VALUES (1, 10000, '2021-04-19', 'Nyurtang', 1);
INSERT INTO `db_bukuhutang`.`bayar` (`id`, `nominal`, `tanggal`, `ket`, `id_penghutang`) VALUES (2, 5000, '2021-04-19', 'Ntes nemu duit ning dalan', 3);
INSERT INTO `db_bukuhutang`.`bayar` (`id`, `nominal`, `tanggal`, `ket`, `id_penghutang`) VALUES (3, 7500, '2021-04-19', 'Dipai duit ning mang Edi', 5);

COMMIT;